[package]
name = "gdext_coroutines"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"
description = "Run Rust coroutines in Godot 4.2+ (through GDExtension), inspired on Unity's Coroutines design."
license = "MIT"
repository = "https://github.com/Houtamelo/gdext_coroutines"
categories = ["game-development", "api-bindings", "asynchronous"]
keywords = ["godot", "coroutines", "gdextension", "async"]
readme = "../README.md"
exclude = [
    ".idea/*"
]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
godot = "0.1.1"

[features]
integration_tests = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]